language: go

# safelist
branches:
  only:
  - master
  - travis

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/modocache/gover

script:
  - ginkgo

after_success:
  - gover . coverage.txt
  - ls -al
  - cat coverage.txt
  - bash <(curl -s https://codecov.io/bash)